#!/usr/bin/env zsh

if [[ $# -gt 0 ]]; then
    echo "usage: $0"
    exit 0
fi

kodi_loc='odroid.local:8080'

curl -X POST -H 'Content-Type: application/json' http://$kodi_loc/jsonrpc\?awx --data-ascii  '{"jsonrpc": "2.0", "method": "Player.Stop", "params" : { "playerid": 1 }, "id": 1}'
